name = "hyperdrive-example"
main = "src/index.ts"
compatibility_date = "2023-09-11"

node_compat = true # required for database drivers to function

# Pasted from the output of `wrangler hyperdrive create $NAME --connection-string=[...]` above.
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "12c76a81bc534682bf499d52454a6c1f"